spring:
  datasource:
    url: jdbc:mysql://hackathonzubei.mysql.database.azure.com:3306/hackathon?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: pkun@hackathonzubei
    password: Li2000chun
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hackathon.backend.entity

logging:
  level:
    ns:
      mental:
        advi:
          dao: debug